const BCRYPT_SALT = 10;

const API_VERSION = 1;

const API_PREFIX = `/api/v${API_VERSION}`;

const IS_PUBLIC_KEY = "isPublic";

const IMAGE_PUBLIC_PATH = "/assets/images/";

const DEFAULT_MAX_ITEM_PER_PAGE = 10;

const MAX_DAY_OF_WEEK = 7;

const DEFAULT_PASSWORD = "AVN12345";

module.exports = {
  BCRYPT_SALT,
  API_PREFIX,
  API_VERSION,
  IS_PUBLIC_KEY,
  DEFAULT_MAX_ITEM_PER_PAGE,
  DEFAULT_MAX_ITEM_PER_PAGE,
  IMAGE_PUBLIC_PATH,
  MAX_DAY_OF_WEEK,
  DEFAULT_PASSWORD,
};
